### ISSUE TITLE
Error in Travis: (Mix) Could not find migrations directory “priv/repo/migrations” for repo Peepchat.Repo

### ISSUE THREAD

**Issue by joepstender** [mike-north/peepchat-api#2]
Following the tutorial at the end of the first part:

> Commit the change, and push it up to GitHub. After travis does its thing, it should automatically deploy to Heroku now.

When I commit the last change to .travis.yml I get an error in Travis: “(Mix) Could not find migrations directory “priv/repo/migrations” for repo Peepchat.Repo”.

I noticed that when I follow the tutorial the current dependencies are:
`defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:cors_plug, "~> 1.1"}]
  end`

Also elixir: “~> 1.2” is used.

I tried to use the older dependencies like you have in your github repo but can’t get it to work that way either. 

Any tips on how to debug this?

**Comment by halilim** [comment]
Put a `.gitkeep` in `priv/repo/migrations` and push again. Relevant: https://github.com/phoenixframework/phoenix/issues/1858

**Comment by joepstender** [comment]
Thanks, that indeed is the underlying issue. Closing this one.
